version: "3"
services:
    redis:
        image: redis
        ports:
            - 6379:6379
        container_name: cache

    node:
        build: .
        ports:
            - 3333:3333
        container_name: node
        depends_on:
            - redis